version: '3.9'
services:
  localstack:
    image: localstack/localstack:2.1
    container_name: localstack
    environment:
      SERVICES: s3,dynamodb
      DEBUG: '1'
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: us-east-1
    ports:
      - '4566:4566'
    volumes:
      - localstack-data:/var/lib/localstack

  api:
    build: .
    container_name: rc-user-crud-api
    depends_on:
      - localstack
    environment:
      PORT: 3000
      AWS_REGION: us-east-1
      AWS_ENDPOINT: http://localstack:4566
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      NODE_ENV: development
    ports:
      - '3000:3000'
    command: sh -c "npm run build && node dist/main"
    # Para hot reload poderia usar: command: npm run start:dev (e montar volume src)
    # volumes:
    #   - ./:/app

volumes:
  localstack-data: {}
