name: rcuc-test
services:
  app:
    container_name: rcuc-test-app
    build:
      context: .
      dockerfile: Dockerfile
      target: testing
    environment:
      - NODE_ENV=testing
      - PORT=3002
    ports:
      - "3002:3002"
    healthcheck:
      test: ["CMD-SHELL", "node -e \"require('net').connect(process.env.PORT||3000,'127.0.0.1').on('connect',()=>process.exit(0)).on('error',()=>process.exit(1))\" "]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: unless-stopped
