name: rcuc-test
services:
  app:
    container_name: rcuc-test-app
    build:
      context: .
      dockerfile: Dockerfile
      target: testing
    command: npm run start:prod
    environment:
      - NODE_ENV=testing
      - PORT=3000
    ports:
      - "3000:3000"
