apiVersion: apps/v1
kind: Deployment
metadata:
  name: ridiculously-complex-api
  labels:
    app: ridiculously-complex-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ridiculously-complex-api
  template:
    metadata:
      labels:
        app: ridiculously-complex-api
    spec:
      containers:
        - name: api
          image: ridiculously-complex-user-crud:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: api-config
