apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  labels:
    app: localstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
        - name: localstack
          image: localstack/localstack:2.1
          env:
            - name: SERVICES
              value: "s3,dynamodb"
            - name: DEBUG
              value: "1"
            - name: DATA_DIR
              value: "/tmp/localstack/data"
          ports:
            - containerPort: 4566 # edge port
          volumeMounts:
            - name: localstack-data
              mountPath: /tmp/localstack
      volumes:
        - name: localstack-data
          emptyDir: {}
